service: mortgage-project
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: python3.8
  apiGateway:
    apiKeys:
      - my_new_key

package:
  exclude:
    - '**/*'
  include:
    - '*.py'
    - 'pandas'
    - 'scipy'
    - 'numpy'

functions:
  deterministic_rules:
    handler: handler.get_mortgage_data
    events:
      - http:
          path: /
          method: get
          private: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true